FROM node:18-alpine as build
COPY . /app
WORKDIR /app
RUN yarn install --frozen-lockfile
RUN yarn build

FROM node:18-alpine
COPY . /app
COPY --from=build /app/dist /app
WORKDIR /app
RUN yarn install --frozen-lockfile
RUN yarn build
EXPOSE 3000
CMD node ./main.js